version: '3.6'
services:
  nginx:
    image: nginx:stable
    container_name: ermeo-v1-webserver
    working_dir: /application
    volumes:
      - ./engine/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    ports:
      - '8080:80'
  php-fpm:
    build:
      context: engine/php-fpm
    container_name: ermeo-v1-php-fpm
    working_dir: /application
    volumes:
      - ./engine/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ./:/application
